/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/// <reference types="vite/client" />
interface ImportMetaEnv {
  readonly BUCKET_NAME: string
  readonly VITE_CHRIS_API: string
}
interface ImportMeta {
  readonly env: ImportMetaEnv
}